### ISSUE TITLE
How exactly would I compile this thing using a command line??

### ISSUE THREAD

**Issue by Illizion** [Kineticraft/source-master#16]
I would really appreciate if you guys left a little tidbit on how to compile this on a Unix shell, as I never have access to a desktop computer to use IntelliJ with

And I'm using a Chromebook with Codenvy, not a phone thank you very much.

**Comment by Illizion** [comment]
@Cassy343 since I can't compile it by command line, can you send me a compiled jar?

**Comment by Sharkykzn** [comment]
This shared source is outdated, as per notice left by FearsomeMango after we went through the process yesterday:
Investigation with the source code with Sharkykzn, Ive discovered the code that is 'open-sourced' out of date to the point of the old ranking system and lack of ComponentBuilderWrapper that is  crucial to working with newer spigot.jar and other updated libraries. I remember this when i was a part of the team (my guess once kc turned into an organization on github, it fell off of the open sourced aspect). Players have an out of date code they are trying to work on and cannot properly work on the code.

**Comment by Egoscio-zz** [comment]
I don't know where you're getting this. Currently, the code on the master branch is the latest. Sometimes, code would be pushed off to other public branches until it would leave the testing phase. A little after the code is sent to production, it would be pulled back into master branch. The "KCsource" repository you forked is indeed out of date. Consider recloning from master's latest commit.

**Comment by Sharkykzn** [comment]
Hi. Take no notice of the "KCsource" repository, it was not what we were using, but had downloaded current master commit from this GitHub. Initial steps tken through with support from FearsomeMango had resulted in various errors and warnings - It is FearsomeMango who informed me that code was outdated, as per reasoning supplied above.

I have persistently attempted a number of retries in building the source code, based on the PaperSpigot-1.12.2-b1474.jar and commit source files from this GitHub. In build I now only get 18 warnings, mainly regarding depreciated src items.

When attempting to use the compiled .jar file on a test server, log shows the following errors attached:
`[23:49:44] [Server thread/INFO]: [Kineticraft] Enabling Kineticraft v1-62
[23:49:44] [Server thread/INFO]: [KCv4] - Registering Mechanics...
[23:49:45] [Server thread/ERROR]: Error occurred while enabling Kineticraft v1-62 (Is it up to date?)
java.lang.NoClassDefFoundError: com/xxmicloxx/NoteBlockAPI/SongPlayer
	at net.kineticraft.lostcity.mechanics.system.MechanicManager.addMechanic(MechanicManager.java:108) ~[?:?]
	at net.kineticraft.lostcity.mechanics.system.MechanicManager.addMechanic(MechanicManager.java:100) ~[?:?]
	at net.kineticraft.lostcity.mechanics.system.MechanicManager.registerDefault(MechanicManager.java:50) ~[?:?]
	at net.kineticraft.lostcity.mechanics.system.MechanicManager.registerMechanics(MechanicManager.java:123) ~[?:?]
	at net.kineticraft.lostcity.Core.onEnable(Core.java:41) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293) [PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassNotFoundException: com.xxmicloxx.NoteBlockAPI.SongPlayer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:566) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:499) ~[?:?]
	... 16 more
[23:49:45] [Server thread/INFO]: [Kineticraft] Disabling Kineticraft v1-62
[23:49:45] [Server thread/INFO]: [KCv4] - Shutting down...
[23:49:45] [Server thread/INFO]: Done (5,309s)! For help, type "help" or "?"
[23:49:45] [Server thread/INFO]: Timings Reset`
